export const productModel = [
  {
    img: "images/producto1.jpg",
    name: "Producto 1",
    text: "Proin condimentum sodales risus ut aliquet. Nunc eu neque quis sapien feugiat posuere sed nec mauris.",
    price: "$1.000.000,00",
    link: "#",
    trolley: "Agregar al carrito",
  },
  {
    img: "images/producto2.jpg",
    name: "Producto 2",
    text: "Proin condimentum sodales risus ut aliquet. Nunc eu neque quis sapien feugiat posuere sed nec mauris.",
    price: "$1.000.000,00",
    link: "#",
    trolley: "Agregar al carrito",
  },
  {
    img: "images/producto3.jpg",
    name: "Producto 3",
    text: "Proin condimentum sodales risus ut aliquet. Nunc eu neque quis sapien feugiat posuere sed nec mauris.",
    price: "$1.000.000,00",
    link: "#",
    trolley: "Agregar al carrito",
  },
  {
    img: "images/producto4.jpg",
    name: "Producto 4",
    text: "Proin condimentum sodales risus ut aliquet. Nunc eu neque quis sapien feugiat posuere sed nec mauris.",
    price: "$1.000.000,00",
    link: "#",
    trolley: "Agregar al carrito",
  },
  {
    img: "images/producto5.jpg",
    name: "Producto 5",
    text: "Proin condimentum sodales risus ut aliquet. Nunc eu neque quis sapien feugiat posuere sed nec mauris.",
    price: "$1.000.000,00",
    link: "#",
    trolley: "Agregar al carrito",
  },
  {
    img: "images/producto6.jpg",
    name: "Producto 6",
    text: "Proin condimentum sodales risus ut aliquet. Nunc eu neque quis sapien feugiat posuere sed nec mauris.",
    price: "$1.000.000,00",
    link: "#",
    trolley: "Agregar al carrito",
  },
];
